#! /usr/bin/env python3
"""
build the sample_sheet.csv file for fabric genomics
the main function is rename the fastq files
"""

import os, sys, re
import logging
from termcolor import colored

import sys
import logging
class CustomFormatter(logging.Formatter):

    colors = {
        'black': '\u001b[30;20m',
        'red': '\u001b[31;20m',
        'r': '\u001b[31;20m',
        'bold_red': '\u001b[31;1m',
        'rb': '\u001b[31;1m',
        'green': '\u001b[32;20m',
        'g': '\u001b[32;20m',
        'gb': '\u001b[32;1m',
        'yellow': '\u001b[33;20m',
        'blue': '\u001b[34;20m',
        'b': '\u001b[34;20m',
        'purple': '\u001b[35;1m',
        'p': '\u001b[35;1m',
        'grey': '\u001b[38;20m',
    }
    FORMATS = {
        logging.WARNING: colors['purple'],
        logging.ERROR: colors['bold_red'],
        logging.CRITICAL: colors['bold_red'],
    }

    def format(self, record):
        format_str = "%(asctime)s  %(levelname)-6s %(funcName)-20s  line: %(lineno)-5s  %(message)s"
        reset = "\u001b[0m"
        log_fmt = None
        
        record.msg = str(record.msg)
        if '@' in record.msg[:10]:
            try:
                icolor, tmp = record.msg.split('@', 1)
                log_fmt = self.colors.get(icolor)
                if log_fmt:
                    record.msg = tmp
            except:
                raise
                pass
        else:
            log_fmt = self.FORMATS.get(record.levelno)
        if log_fmt:
            record.msg = log_fmt + record.msg + reset
        formatter = logging.Formatter(format_str, datefmt='%Y-%m-%d %H:%M:%S')
        return formatter.format(record)

console = logging.StreamHandler(sys.stdout)
console.setFormatter(CustomFormatter())
console.setLevel('INFO')
try:
    logger = logging.getLogger(__file__)
except:
    logger = logging.getLogger('terminal')
logger.setLevel('DEBUG')
logger.addHandler(console)

def colored(text, color=None, on_color=None, attrs=None):
    # Copyright (c) 2008-2011 Volvox Development Team
    #
    # Permission is hereby granted, free of charge, to any person obtaining a copy
    # of this software and associated documentation files (the "Software"), to deal
    # in the Software without restriction, including without limitation the rights
    # to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    # copies of the Software, and to permit persons to whom the Software is
    # furnished to do so, subject to the following conditions:
    #
    # The above copyright notice and this permission notice shall be included in
    # all copies or substantial portions of the Software.
    #
    # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    # IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    # FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    # AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    # LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
    # THE SOFTWARE.
    #
    # Author: Konstantin Lepa <konstantin.lepa@gmail.com>

    ATTRIBUTES = dict(
            list(zip([
                'bold',
                'dark',
                '',
                'underline',
                'blink',
                '',
                'reverse',
                'concealed'
                ],
                list(range(1, 9))
                ))
            )
    del ATTRIBUTES['']


    HIGHLIGHTS = dict(
            list(zip([
                'on_grey',
                'on_red',
                'on_green',
                'on_yellow',
                'on_blue',
                'on_magenta',
                'on_cyan',
                'on_white'
                ],
                list(range(40, 48))
                ))
            )


    COLORS = dict(
            list(zip([
                'grey',
                'red',
                'green',
                'yellow',
                'blue',
                'magenta',
                'cyan',
                'white',
                ],
                list(range(30, 38))
                ))
            )


    RESET = '\u001b[0m'
    if os.getenv('ANSI_COLORS_DISABLED') is None:
        fmt_str = '\u001b[%dm%s'
        if color is not None:
            text = fmt_str % (COLORS[color], text)

        if on_color is not None:
            text = fmt_str % (HIGHLIGHTS[on_color], text)

        if attrs is not None:
            for attr in attrs:
                text = fmt_str % (ATTRIBUTES[attr], text)

        text += RESET
    return text

def red(s):
    return colored(s, 'red', attrs=['bold'])
def green(s):
    return colored(s, 'green', attrs=['bold'])


def rename_fq(fn, relation_map, case_prefix, kw_dedup, d_sam_sn):
    fn_pure = os.path.basename(fn)
    fn = os.path.realpath(fn)
    relation_map = relation_map or {}

    if not fn.endswith('.fastq.gz'):
        logger.warning(f'non fastq file found, ignored: {fn}')
        return None
    fn_lite = re.sub('[._-]R[12]\.fastq\.gz', '', fn_pure)
    fn_lite = re.sub(r'L0\d{2}[_.]', '', fn_lite)

    try:
        sam_sn = d_sam_sn[fn_lite]
    except:
        sam_sn = d_sam_sn['current'] + 1
        d_sam_sn[fn_lite] = sam_sn
        d_sam_sn['current'] += 1

    sam_sn = f'{sam_sn:>02}'

    m_r12 = re.match(r'.*[._-](R[12])', fn_pure)
    if m_r12:
        r12 = m_r12.group(1)
    else:
        logger.error(f'R1/R2 not found in file name: {fn}')
        return None

    m = re.match(r'.*{L0\d{2}}[_.]', fn_pure)
    if m:
        lane_info = m.group(1)
    else:
        lane_info = 'L001'

    relation = ''
    for kw, family_relation in relation_map.items():
        kw = kw.lower()
        if fn_pure.lower().find(kw) > -1:
            kw_dedup.setdefault(kw, set()).add(fn_lite)
            relation = f'-{family_relation}'
            break

    lb = fn_pure.split('_', 1)[0]
    if len(lb) < 4:
        logger.warning(f'invalid fastq name, the string before first underscore should be unique sample name')
        return None

    # {prefix}_S0{sample_sn}_L001_R1/R2_001.fastq.gz

    sample_ID = f'{case_prefix}{relation}-{lb}'
    new_fn = f'{sample_ID}_S{sam_sn}_{lane_info}_{r12}_001.fastq.gz'

    fn_full = f'{pw_fq}/{new_fn}'
    if not os.path.exists(fn_full):
        try:
            os.symlink(fn, fn_full)
        except:
            logger.error(f'fail to create the symlink for {fn}, newname = {new_fn}')
            raise
            return None

    return sample_ID

def red(s):
    return colored(s, 'red')


def build_sample_sheet(case, res, fabric_prj, report_type, assay_type, job_type, test_id):
    fn_sample_sheet = f'{case}_samplesheet.csv'
    with open(fn_sample_sheet, 'w') as o:
        print(f"""[Header],,,,,,,
{case}(Case Name),,,,,,,
[Reads],,,,,,,
,,,,,,,
[Settings],,,,,,,
,,,,,,,
[Data],,,,,,,
Sample_ID,Sample_Name,project,sex,report_type,assay_type,job_type,test_id""", file=o)
        for i in res:
            print(f'{i},{i},{fabric_prj},unspecified,{report_type},{assay_type},{job_type},{test_id}', file=o)


    with open('fabric_upload.sh', 'w') as o:
        print(f"fabric_upload  {pw_fq}  --sample-sheet {fn_sample_sheet} --instrument-run-id {case}", file=o)

    return 'fabric_upload.sh'

def parse_relation_map(relation_map):
    if relation_map is None:
        return {}

    res = {}
    invalid = 0
    for i in relation_map:
        try:
            k, v = i.split(':')
        except:
            logger.error(f'invalid relation map: {i}, should contain 1 and only 1 colon')
            invalid += 1
            continue
        res[k] = v
    if invalid > 0:
        logger.error('exit now')
        sys.exit(1)
    return res

def get_fqlist(pwdata):
    tmp = os.popen(f'find -L {pwdata} -type f -iname "*.fastq.gz"').read().strip().split('\n')
    return tmp

if __name__ == "__main__":

    warning_str = red("don't modify if not sure ")
    import argparse as arg
    from argparse import RawTextHelpFormatter
    ps = arg.ArgumentParser(description=__doc__, formatter_class=RawTextHelpFormatter)
    ps.add_argument("case",  help="case / project prefix, usually the case name, must specify")
    ps.add_argument("fq", help="fastq file list, or the folder containing the fastq files, e.g. download/", nargs='+')
    ps.add_argument("-map", '-m',  help="name map, will try to use this map to add the Proband, Father or mother str, format is like : 005628:Proband", nargs='*')
    ps.add_argument('-report_type', "-rep",  help=warning_str + "report type, default=solo", choices=['solo', 'trio'], default='solo')
    ps.add_argument("-job_type", '-j',  help=warning_str + "job type, usually secondary_haplotyper", default="secondary_haplotyper")
    ps.add_argument("-assay_type", '-aid',  help=warning_str + "pre-built secondary analysis assay UID, default=1237381", default="1237381")
    ps.add_argument("-test_id", '-tid',  help=warning_str + "pre-built test pipeline UID, default=1237385", default="1237385")
    ps.add_argument("-fabric_prj", '-fabprj',  help=warning_str + "fabric genomic project name, usually always UDP samples", default="UDP samples")


    args = ps.parse_args()


    fqlist = args.fq
    relation_map = args.map
    case_prefix = args.case
    report_type = args.report_type
    job_type = args.job_type
    assay_type = args.assay_type
    test_id = args.test_id
    fabric_prj = args.fabric_prj

    if len(fqlist) == 1 and os.path.isdir(fqlist[0]):
        fqlist = get_fqlist(fqlist[0])


    if len(fqlist) == 0:
        logger.error(f'no fqlist specified')

    pw_fq = 'fabric_data'
    os.makedirs(pw_fq, exist_ok=True)

    relation_map = parse_relation_map(relation_map)

    logger.info(relation_map)
    
    invalid = []
    res = set()
    kw_dedup = {}
    d_sam_sn = {'current': 0}
    for fn in fqlist:
        sample_id = rename_fq(fn, relation_map, case_prefix, kw_dedup, d_sam_sn)
        if sample_id is None:
            invalid.append(fn)
            continue
        res.add(sample_id)

    res = sorted(res)
    if len(invalid) > 0:
        logger.error(red(f'the following {len(invalid)} file name are invalid: plese check\n\t' + '\n\t'.join(invalid)))
        sys.exit(1)

    fn_script = build_sample_sheet(case_prefix, res, fabric_prj, report_type, assay_type, job_type, test_id)

    logger.info(f'all done, please check and run {fn_script} to upload the file')
