#! /usr/bin/env python3
import os, sys, re
import logging
from string import Template

fmt = logging.Formatter('%(asctime)s  %(levelname)-9s %(funcName)-25s  line: %(lineno)-5s  %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
# fmt = logging.Formatter('%(asctime)s  %(levelname)-9s  line: %(lineno)-5s  %(message)s', datefmt='%Y-%m-%d %H:%M:%S')
console = logging.StreamHandler(sys.stdout)
console.setFormatter(fmt)
console.setLevel('INFO')
try:
    logger = logging.getLogger(__file__)
except:
    logger = logging.getLogger('terminal')
logger.setLevel('DEBUG')
logger.addHandler(console)

import argparse as arg
from argparse import RawTextHelpFormatter
ps = arg.ArgumentParser(description=__doc__, formatter_class=RawTextHelpFormatter)
ps.add_argument('pos', help="""the coordinate, hg38, should be like chr1:123-456, if multiple, sep by space""", nargs='+')
args = ps.parse_args()

vcf = """
##fileformat=VCFv4.1
##ALT=<ID=CNV,Description="Copy number variant region">
##ALT=<ID=DEL,Description="Deletion relative to the reference">
##ALT=<ID=DUP,Description="Region of elevated copy number relative to the reference">
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr10,length=133797422>
##contig=<ID=chr11,length=135086622>
##contig=<ID=chr12,length=133275309>
##contig=<ID=chr13,length=114364328>
##contig=<ID=chr14,length=107043718>
##contig=<ID=chr15,length=101991189>
##contig=<ID=chr16,length=90338345>
##contig=<ID=chr17,length=83257441>
##contig=<ID=chr18,length=80373285>
##contig=<ID=chr19,length=58617616>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr20,length=64444167>
##contig=<ID=chr21,length=46709983>
##contig=<ID=chr22,length=50818468>
##contig=<ID=chr3,length=198295559>
##contig=<ID=chr4,length=190214555>
##contig=<ID=chr5,length=181538259>
##contig=<ID=chr6,length=170805979>
##contig=<ID=chr7,length=159345973>
##contig=<ID=chr8,length=145138636>
##contig=<ID=chr9,length=138394717>
##contig=<ID=chrX,length=156040895>
##reference=file:///mnt/pure2/reference/human/hg38/hg38.fa.default/
##INFO=<ID=SVTYPE,Number=1,Type=String,Description="Type of structural variant">
##INFO=<ID=END,Number=1,Type=Integer,Description="End position of the variant described in this record">
##INFO=<ID=CIPOS,Number=2,Type=Integer,Description="Confidence interval around POS">
##INFO=<ID=CIEND,Number=2,Type=Integer,Description="Confidence interval around END">
##FILTER=<ID=cnvQual,Description="CNV with quality below 10">
##FILTER=<ID=cnvCopyRatio,Description="CNV with copy ratio within +/- 0.2 of 1.0">
##FORMAT=<ID=SM,Number=1,Type=Float,Description="Linear copy ratio of the segment mean">
##FORMAT=<ID=CN,Number=1,Type=Integer,Description="Estimated copy number">
##FORMAT=<ID=BC,Number=1,Type=Integer,Description="Number of bins in the region">
##FORMAT=<ID=PE,Number=2,Type=Integer,Description="Number of improperly paired end reads at start and stop breakpoints">
##DRAGENCommandLine=<ID=dragen,Date="Wed Dec 16 16:21:23 UTC 2020",CommandLineOptions=" --ref-dir=/mnt/pure2/reference/human/hg38/hg38.fa.default/ --output-directory /mnt/pure/rnd/WGS_V3/WGS/HTFNLDSXY/939019_S1/ --output-file-prefix 939019_S1.slm --enable-map-align=false --enable-cnv=true --cnv-input /mnt/pure/rnd/WGS_V3/WGS/HTFNLDSXY/939019_S1/939019_S1.target.counts.gc-corrected --cnv-normals-list=/mnt/pure/rnd/WGS_validation/FemaleNormals_validation_test.txt --cnv-segmentation-mode=slm --cnv-enable-gcbias-correction=false">
##DRAGENVersion=<ID=dragen,Version="SW: 01.011.264.3.1.7, HW: 01.011.264">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  sample1
"""
# chr1    1       DRAGEN:LOSS:1:9998      N       <DEL>   71      PASS    SVTYPE=CNV;END=9998;SVLEN=9997  SM:CN:BC:PE     9.67817e-10:0:20:0,61
# chr1    9999    DRAGEN:LOSS:9999:10498  N       <DEL>   3       cnvQual SVTYPE=CNV;END=10498;SVLEN=499  SM:CN:BC:PE     0.896367:2:1:61,65

# parse the pos
rows = []
for ipos_raw in args.pos:
    ipos = ipos_raw.strip().lower()
    ipos = re.sub(r'\s+', '', ipos)
    m = re.match(r'(?:chr)?([\dxym]+)[:_\-](\d+)[_-](\d+)', ipos)
    if not m:
        logger.warning(f'wrong coordinate format: {ipos_raw}')
        continue
    chr_, s, e = m.groups()
    len1 = int(e) - int(s)
    irow = f'chr{chr_}\t{s}\tDRAGEN:LOSS:{s}:{e}\tN\t<DEL>\t 100\tPASS\tSVTYPE=CNV;END={e};SVLEN={len1}\tSM:CN:BC:PE\t9.67817e-10:0:20:0,61'
    rows.append(irow)

fn_vcf = f'tmp.check_dgv.vcf'
with open(fn_vcf, 'w') as o:
    vcf += '\n'.join(rows)

    print(vcf, file=o)

dock_path = '/nobackup/cqs/chenh19/dock/annotsv.sif'
annot_sv_app = f'singularity exec {dock_path}  /tools/AnnotSV/bin/AnnotSV'

cmd = f'{annot_sv_app} -genomeBuild GRCh38 -typeOfAnnotation split -SVinputFile {fn_vcf}'
logger.debug(cmd)
os.system(cmd)
