#! /usr/bin/env python3
from omim_utils import omim_query
from amelie_utils import query_amelie
from chctool_lite import getlogger

import os, sys

logger = getlogger('omim_query')


pw = os.getcwd()
prj = os.path.basename(pw)

tmp = f'{pw}/intermediate/{prj}.terms_pure_hpo.txt'
err = 0
if not os.path.exists(tmp):
    logger.error(f'hpo term file not exist: {tmp}')
    err = 1

tmp = f'{pw}/intermediate/{prj}.genelist'
if not os.path.exists(tmp):
    logger.error(f'genelist file not exist: {tmp}')
    err = 1

d_amelie = query_amelie(pw, prj, logger=logger, force=False)
